# 你的状态页显示的用户名
owner: pandax-i
repo: status

sites:
  - name: 耗子面板入口
    url: http://106.55.149.12
    # 如果不想让别人看到面板端口，可以把这个删掉

  - name: 我的博客
    url: https://www.example.com
    method: GET
    expectedStatusCodes:
      - 200

status-website:
  # 状态页的自定义域名 (后面第四步会讲，没有就先注释掉)
  # cname: status.example.com
  
  # 状态页左上角的 Logo 和 标题
  logoUrl: https://raw.githubusercontent.com/upptime/upptime/master/assets/icon.svg
  name: 我的服务监控
  introTitle: 系统状态正常
  introMessage: 这里监控着我所有的服务状态。
  navbar:
    - title: 状态
      url: /
    - title: GitHub
      url: https://github.com/$OWNER/$REPO

# 国际化配置 (让界面显示中文)
i18n:
  activeIncidents: 活动事件
  allSystemsOperational: 所有系统运行正常
  incidentReport: 事件报告
  latestIncidents: 最新事件
